---
#Network
hostname: koombook.lan
hotspot_name: koombook
wpa_pass: KBcampus

use_hdd: True
send_to_central_server: True
import_ideascube_data: False
download_data: False

#Apps path
mook_upload_file_path: /media/hdd/{{ mook_name }}/static/

#Hardware battery for Olimex Lime2
battery_capacity: 7800
charging_current: 750
power_on_button_delay: 500
power_off_button_delay: 8000
enable_power_button_power_off: 1
