---
#Network
hostname: koombook.lan
hotspot_name: koombook
wpa_pass: KBcampus

#Apps path
software_path: /media/hdd/framadvd/
zim_path: /media/hdd
mook_upload_file_path: /media/hdd/{{ mook_name }}/static/