---
#Network
hostname: ideasbox.lan
hotspot_name: ideasbox
ideascube_project_name: ideasbox
ideascube_branding: ideasbox
managed_by_bsf: True
old_kiwix_path: /usr/local/share/kiwix/data
samba_dir: /srv/
