---
- name: Install nginx web server
  apt: pkg=nginx state=installed force=yes

- name: Remove default nginx vhost config file (if configured).
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Upload nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  notify: restart nginx

- name: Copy redirect 301 rules to redirect old kiwix links
  copy: src=redirect dest=/etc/nginx/sites-available/redirect

- name: Enable Virtual host
  file: src=/etc/nginx/sites-available/redirect dest=/etc/nginx/sites-enabled/redirect state=link
  notify: restart nginx