---
####
# BACK END CONFIGURATION
####
- name: Clone mook api
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/gryzzlab/mook-bsf-api.git dest={{ mook_path }}/{{ mook_name }}/api accept_hostkey=yes

####
# FRONT END CONFIGURATION
####
- name: Clone mook front
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/gryzzlab/mook-bsf-front-end-backbone.git dest={{ mook_path }}/{{ mook_name }}/front accept_hostkey=yes

- name: Create data directory
  file: path={{ mook_path }}/{{ mook_name }}/static/tmp state=directory mode=0755 owner={{ username }} group={{ username }}

- tasks:
  include: ../../../post_tasks.yml task=mook version=1
  