---
- include: ../../../pre_install.yml task=mongodb

- include: mongodb_{{ ansible_architecture }}.yml
  #when: ansible_local.installed_software.software.mongodb < "{{ version }}"

- include: ../../../post_install.yml task=mongodb task_version=""
  #when: ansible_local.installed_software.software.mongodb < "{{ version }}"