---
- include: ../../../pre_install.yml task=mongodb

- include: mongodb_{{ ansible_architecture }}.yml

- include: ../../../post_install.yml task=mongodb task_version="{{ ansible_local.device_list[ideascube_device_name].mongodb.version }}"