---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Open all outgoing connection to allow NFS, dirty but working ! 
  command: iptables -t filter -I OUTPUT -j ACCEPT

- name: Install nfs-common
  apt: name=cifs-utils state=present

- name: Create a working dir for NFS shared
  file: path=/media/synology/ state=directory

- name: Mount CIFS Share
  mount:
    name: /media/synology
    src: //{{kawax}}/content
    fstype: cifs
    opts: guest
    state: mounted

- name: Copy kalite videos
  synchronize: src=/media/synology/videosKalite/{{ item }}/ 
    dest=/home/{{username}}/.kalite/content/ 
    recursive=yes
    compress=no
  with_items: "{{ ansible_local.device_list[generic_project_name].kalite.language }}"

- name: Unmount shared folder from a NFS Share
  command: umount /media/synology

- name: Set permission back to the user instead of root after importing the medias
  file: path=/home/{{username}}/.kalite/content/ owner={{ username }} group={{ username }}  mode="u=rwX,go=rX" recurse=yes
