---
- include: kalite.yml
  when: ansible_local.tracking_update.upgrade.kalite < "{{ version }}"

- include: ../../../post_tasks.yml task=kalite version={{ version }}
  when: ansible_local.tracking_update.upgrade.kalite < "{{ version }}"