---
- include: ../../../pre_install.yml task=kalite
  tags: ['custom', 'update']

- include: kalite.yml

- include: ../../../post_install.yml task=kalite task_version="{{ kalite_version }}"
  tags: ['custom', 'update']