---
- name: Install kalite
  pip: name=ka-lite-static

- file: path=/home/ideascube/.kalite/content state=absent

- file: src=/media/hdd/khanVideos/content/ dest=/home/ideascube/.kalite/content state=link

- name: Fix rights
  file: path=/media/hdd/khanVideos/content/ state=directory owner={{ username }} group={{ username }} recurse=yes

- name: Copy nginx vhost
  template: src=kalite.vhost.j2 dest=/etc/nginx/sites-available/kalite

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kalite dest=/etc/nginx/sites-enabled/kalite state=link
  notify: restart nginx

- name: Setup startup file
  template: src=kalite.j2 dest=/etc/init.d/kalite owner=root group=root mode="u+x"

- name: Enable service kalite
  service: name=kalite enabled=yes

# Has to be done by hand...
# $> sudo su -s /bin/bash ideascube
# $> kalite manage setup

- tasks:
  include: ../../../post_tasks.yml task=kalite version=1
