---
- include: ../../../pre_install.yml task=kalite
  tags: ['custom', 'update']

- include: kalite.yml

- include: ../../../post_install.yml task=kalite task_version="{{ ansible_local.device_list[generic_project_name].kalite.version }}"
  tags: ['custom', 'update']