---
- name: Check if kalite is installed
  command: dpkg-query -W ka-lite-raspberry-pi
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"
  register: kalite_check_deb
  failed_when: kalite_check_deb.rc > 1
  changed_when: kalite_check_deb.rc == 1

- name: download Ka lite
  get_url: url={{filer_bsf}}/kalite014ARM.deb dest=/home/kalite014ARM.deb
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and kalite_check_deb.rc == 1

- shell: export DEBIAN_FRONTEND=noninteractive
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and kalite_check_deb.rc == 1

- name: configure kalite
  debconf: name=ka-lite-raspberry-pi question='ka-lite/user' value='ka-lite' vtype='string'
  debconf: name=ka-lite-raspberry-pi question='ka-lite/init' value='true' vtype='boolean'
  debconf: name=ka-lite-raspberry-pi question='ka-lite/download-assessment-items' value='false' vtype='boolean'
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and kalite_check_deb.rc == 1

- name: install kalite
  apt: deb=/home/kalite014ARM.deb force=yes
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and kalite_check_deb.rc == 1

- file: path=/var/ka-lite/.kalite/content state=absent
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

- file: src=/media/hdd/khanVideos/content/ dest=/var/ka-lite/.kalite/content state=link
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

- name: Fix rights
  file: path=/media/hdd/khanVideos/content/ state=directory owner=ka-lite group=ka-lite recurse=yes

- file: path=/etc/nginx/sites-enabled/kalite.conf state=absent

- name: Copy nginx vhost
  template: src=kalite.vhost.j2 dest=/etc/nginx/sites-available/kalite

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kalite dest=/etc/nginx/sites-enabled/kalite state=link
  notify: restart nginx

- tasks:
  include: ../../../post_tasks.yml task=kalite version=1