---
- stat: path=/media/hdd/ideascube/storage/main/media/mediacenter/document/administrationIdeascube.webm
  register: st

- file: path=/media/hdd/ideascube/ state=absent
  when: st.stat.exists == False

- name: Create storage dir for ideascube
  file: path=/media/hdd/ideascube/storage/main state=directory owner={{ username }} group={{ username }}
  when: st.stat.exists == False

- name: Ideascube collectstatic
  become: yes
  become_user: ideascube
  shell: ideascube collectstatic --noinput
  when: st.stat.exists == False

- name: Ideascube migrate
  become: yes
  become_user: ideascube
  shell: ideascube migrate
  notify: restart uwsgi
  when: st.stat.exists == False

- name: Download backup
  get_url: url={{filer_bsf}}/kb_bsfcampus_cmr-0.4.0-201511041101.tar.gz dest=/tmp/kb_bsfcampus_cmr-0.4.0-201511041101.tar.gz
  when: st.stat.exists == False

- name: Import backup 
  become: yes
  become_user: ideascube
  shell: ideascube backup restore /tmp/kb_bsfcampus_cmr-0.4.0-201511041101.tar.gz
  when: st.stat.exists == False

- name: Download new videos
  get_url: url={{filer_bsf}}/videosIdeascube.zip dest=/media/hdd/videosIdeascube.zip
  when: st.stat.exists == False

- name: unarchive videos
  unarchive: src=/media/hdd/videosIdeascube.zip dest=/media/hdd/IdeasServerContent/videos/ copy=no
  when: st.stat.exists == False

- name: Delete existing csv file
  file: path=/media/hdd/IdeasServerContent/videos/KB_Liste_contenus_bsf_campus.csv state=absent
  ignore_errors: yes
  when: st.stat.exists == False

- name: Download CSV to import
  get_url: url={{filer_bsf}}/KB_Liste_contenus_bsf_campus.csv dest=/media/hdd/IdeasServerContent/videos/KB_Liste_contenus_bsf_campus.csv
  when: st.stat.exists == False

- name: Import CSV 
  become: yes
  become_user: ideascube
  shell: ideascube import_medias /media/hdd/IdeasServerContent/videos/KB_Liste_contenus_bsf_campus.csv
  notify: restart uwsgi
  when: st.stat.exists == False

- tasks:
  include: ../../../post_tasks.yml task=updateIdeascube version={{ version }}
  when: st.stat.exists == False