---
- name: Create storage dir for ideascube
  file: path=/media/hdd/ideascube/storage/main state=directory owner={{ username }} group={{ username }}

- name: Ideascube collectstatic
  become: yes
  become_user: ideascube
  shell: ideascube collectstatic --noinput

- name: Ideascube migrate
  become: yes
  become_user: ideascube
  shell: ideascube migrate
  notify: restart uwsgi

- name: Download CSV to import
  get_url: url={{filer_bsf}}/KB_Liste_contenus_videos+fiches.csv dest=/media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv

- name: Import data 
  become: yes
  become_user: ideascube
  shell: ideascube import_medias /media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv

# - name: Import backup 
#   become: yes
#   become_user: ideascube
#   shell: ideascube backup restore {{filer_bsf}}/backupIdc.tar.gz

- tasks:
  include: ../../../post_tasks.yml task=updateIdeascube version={{ version }}
  when: ideascube_version.stdout <= "{{ version }}"