---
#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable 
    - role: firstStart
      timezone: Africa/Brazzaville
      ideascube_id: "kb_mooc_cog"
      mook_name: ""
