---
- hosts: localhost
#- hosts: SystemPushInstall

  roles:
    - { role: set_custom_fact, tags: [ 'master', 'custom', 'update' ] }
    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix

    - role: app_inventory
      when: ansible_local.installed_software.management.inventory is not defined

    - role: logs
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags:
        - update

    - role: tinc-static
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags: ['custom', 'update']

    - role: kalite
      when: ansible_local.device_list[ideascube_device_name].kalite is defined
        and ansible_local.device_list[ideascube_device_name].kalite.activated|bool == True
      tags: ['custom', 'update']

    - role: mongodb
      when: ansible_local.device_list[ideascube_device_name].mongodb is defined
        and ansible_local.device_list[ideascube_device_name].mongodb.activated|bool == True
      tags: ['custom', 'update']

    - role: mook
      mook_name: bsfcampus
      mook_version: "{{ ansible_local.device_list[ideascube_device_name].bsfcampus.version }}"
      when: ansible_local.device_list[ideascube_device_name].bsfcampus is defined
        and ansible_local.device_list[ideascube_device_name].bsfcampus.activated|bool == True
      tags: ['custom', 'update']

    - role: mook
      mook_name: koombookedu
      mook_version: "{{ ansible_local.device_list[ideascube_device_name].koombookedu.version }}"
      when: ansible_local.device_list[ideascube_device_name].koombookedu is defined
        and ansible_local.device_list[ideascube_device_name].koombookedu.activated|bool == True
      tags: ['custom', 'update']

    - role: zim_install
      when: ansible_local.device_list[ideascube_device_name].zim_install is defined
        and ansible_local.device_list[ideascube_device_name].zim_install.activated|bool == True
      tags: ['custom', 'update']

    - role: idc_import
      when: ansible_local.device_list[ideascube_device_name].idc_import is defined
        and ansible_local.device_list[ideascube_device_name].idc_import.activated|bool == True
      tags: ['custom', 'update']
