---
- hosts: localhost
# - hosts: SystemPushInstall
  gather_facts: False
  pre_tasks:
   - setup:
       filter: 'ansible_hostname'
     tags: ['master', 'custom', 'update']

   - setup:
       filter: 'ansible_architecture'
     tags: ['master', 'custom', 'update']

   - setup:
       filter: 'ansible_date_time'
     tags: ['master', 'custom', 'update']

   - setup:
       filter: 'ansible_distribution_release'
     tags: ['master', 'custom', 'update']

   - setup:
       filter: 'ansible_default_ipv4'
     tags: ['custom', 'update']
     
   - setup:
       filter: 'ansible_machine_id'
     tags: ['custom', 'update']

  roles:
    - { role: set_custom_fact, tags: [ 'master', 'custom', 'update' ] }
    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix

    - role: app_inventory
      when: ansible_local.installed_software.management.inventory is not defined

    - role: logs
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags:
        - update

    - role: tinc-static
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True
      tags: ['custom', 'update']

    - role: kalite
      when: ansible_local.device_list[generic_project_name].kalite is defined
        and ansible_local.device_list[generic_project_name].kalite.activated|bool == True

    - role: mook
      mook_name: bsfcampus
      mook_version: "{{ ansible_local.device_list[generic_project_name].bsfcampus.version }}"
      when: ansible_local.device_list[generic_project_name].bsfcampus is defined
        and ansible_local.device_list[generic_project_name].bsfcampus.activated|bool == True

    - role: mook
      mook_name: koombookedu
      mook_version: "{{ ansible_local.device_list[generic_project_name].koombookedu.version }}"
      when: ansible_local.device_list[generic_project_name].koombookedu is defined
        and ansible_local.device_list[generic_project_name].koombookedu.activated|bool == True

    - role: zim_install
      when: ansible_local.device_list[generic_project_name].zim_install is defined
        and ansible_local.device_list[generic_project_name].zim_install.activated|bool == True
      tags: ['custom', 'update']

    - role: idc_import
      when: ansible_local.device_list[generic_project_name].idc_import is defined
        and ansible_local.device_list[generic_project_name].idc_import.activated|bool == True
      tags: ['custom', 'update']
