---
- hosts: localhost
# - hosts: SystemPushInstall

  roles:
    - { role: set_custom_fact, tags: [ 'master', 'custom', 'update','idc_import','zim_install','kalite_import' ] }
    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix

    - role: tinc-static
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: tinc-dynamic
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: zim_install
      when: ansible_local.device_list[generic_project_name].zim_install is defined
        and ansible_local.device_list[generic_project_name].zim_install.activated|bool == True
      tags: ['custom', 'update','zim_install']

    - role: mook
      mook_name: bsfcampus
      mook_version: "{{ ansible_local.device_list[generic_project_name].bsfcampus.version }}"
      when: ansible_local.device_list[generic_project_name].bsfcampus is defined
        and ansible_local.device_list[generic_project_name].bsfcampus.activated|bool == True

    - role: mook
      mook_name: koombookedu
      mook_version: "{{ ansible_local.device_list[generic_project_name].koombookedu.version }}"
      when: ansible_local.device_list[generic_project_name].koombookedu is defined
        and ansible_local.device_list[generic_project_name].koombookedu.activated|bool == True

    - role: appinventor
      when: ansible_local.device_list[generic_project_name].appinventor is defined
        and ansible_local.device_list[generic_project_name].appinventor.activated|bool == True
      tags: ['custom']

    - role: kalite
      when: ansible_local.device_list[generic_project_name].kalite is defined
        and ansible_local.device_list[generic_project_name].kalite.activated|bool == True

    - role: logs
      when: ansible_local.installed_software.management.managed_by_bsf|bool == True

    - role: idc_import
      when: ansible_local.device_list[generic_project_name].idc_import is defined
        and ansible_local.device_list[generic_project_name].idc_import.activated|bool == True
        and ansible_default_ipv4.gateway == "{{ gateway }}"
      tags: ['custom', 'update','idc_import']
