---
#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable 
    - systemInit
    - nginx
    - dnsmasq
    - hostapd
    - iptables
    - uwsgi
    # - kalite
    # Can be enable/disable on demand but affect all devices

    - role: ideascube
      version: "0.5.0-1"
      ideascube_id: "{{projectName}}"

    # - appinventor
    # #   when: ansible_hostname == 'KoomBook483'

    # # Update Mook plateform
    # - mongodb
    # - { role: mook, mook_name: bsfcampus }
    # - { role: mook, mook_name: fun }

    # Install and configure a kiwix project 
    - role: kiwix
      kiwixProject: wikipedia
      portProject: 8002
      version: "wikipedia_fr_all_2015-11.zim"
    # - role: kiwix
    #   kiwixProject: wikisource
    #   portProject: 8003
    #   version: "wikipedia_fr_all_2015-11.zim"
    # - role: kiwix
    #   kiwixProject: vikidia
    #   portProject: 8004
    # - role: kiwix
    #   kiwixProject: cpassorcier
    #   portProject: 8005
    # - role: kiwix
    #   kiwixProject: ubuntudoc
    #   portProject: 8006
    - role: kiwix
      kiwixProject: gutenberg
      portProject: 8007
      version: "gutenberg_fr_all_10_2014.zim"
    # - role: kiwix
    #   kiwixProject: universcience
    #   portProject: 8009
    # - role: kiwix
    #   kiwixProject: ted
    #   portProject: 8010
    # - role: kiwix
    #   kiwixProject: software
    #   portProject: 8011

    # Play a role for a specific device
    #- { role: iptables, when: ansible_hostname == 'KoomBook603' }
    #- { role: ideascube, when: ansible_hostname == 'KoomBook484' }

    - role: firstStart
      timezone: Europe/Paris
      ideascube_id: "{{projectName}}"
      mook_name: ""

  post_tasks:
    # - command: /sbin/shutdown -h now
    - command: reboot
