---
#It will be always localhost
- hosts: localhost
# - hosts: SystemPushInstall

  roles:
    # Has to be always enable 
    # - systemInit
    # - nginx
    # - dnsmasq
    # - hostapd
    # - iptables
    # - uwsgi
    # - kalite
    # Can be enable/disable on demand but affect all devices
    # - software

    # - role: ideascube
    #   version: "0.5.0-1"

    # - appinventor
    # #   when: ansible_hostname == 'KoomBook483'

    # # Update Mook plateform
    # - mongodb
    # - { role: mook, mook_name: mooc }
    # - { role: mook, mook_name: fun }

    # Install and configure a kiwix project 
    - role: kiwix
      kiwixProject: wikipedia
      portProject: 8002
      version: ['wikipedia_tum_all_nopic_2015-10.zim','wikipedia_tum_all_nopic_2015-09.zim']
    # - role: kiwix
    #   kiwixProject: wikisource
    #   portProject: 8003
    #   version: "wikipedia_fr_all_2015-11.zim"
    - role: kiwix
      kiwixProject: vikidia
      portProject: 8004
      version: ""
    # - role: kiwix
    #   kiwixProject: cpassorcier
    #   portProject: 8005
    # - role: kiwix
    #   kiwixProject: ubuntudoc
    #   portProject: 8006
    - role: kiwix
      kiwixProject: gutenberg
      portProject: 8007
      version: "gutenberg_fr_all_10_2014.zim"
    # - role: kiwix
    #   kiwixProject: universcience
    #   portProject: 8009
    # - role: kiwix
    #   kiwixProject: ted
    #   portProject: 8010
    # - role: kiwix
    #   kiwixProject: software
    #   portProject: 8011

    # Play a role for a specific device
    #- { role: iptables, when: ansible_hostname == 'KoomBook603' }
    #- { role: ideascube, when: ansible_hostname == 'KoomBook484' }

    - role: firstStart
      mook_name: ""

  post_tasks:
    - command: /sbin/shutdown -h now
    - command: reboot
