---
# Ansible playbook for Kytabu

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs

    - role: idc_import
      content_name: "15-logiciel-libre/app.csv"