---
# Ansible playbook for TV5 Monde BDI

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs
    - kalite
    - role: kiwix
      kiwixProject: gutenberg
      portProject: 8002
      lang: ['fr']
    - ideascube

    - { role: tinc-static, when: ansible_hostname == 'kb-bdi-tv5monde-821' }