---
- hosts: localhost

  roles:
    # Enable or disable to suit your needs

    # This role automatically send logs to central server each time the device gets an Internet connection 
    - logs

    - tinc-static

    - role: zim_install
      zim_name: "wikipedia.fr wikipedia.wo wiktionary.fr wikiversity.fr wikisource.fr tedxgeneva2014.fr tedxlausanne2012.fr tedxlausanne2013.fr tedxlausanne2014.fr cest-pas-sorcier.fr dirtybiology.fr gutenberg.fr ubuntudoc.fr wikistage.fr"

    - role: idc_import
      content_name: "8-Sénégal/Contenus/content.csv"