---
# Ansible playbook for LWB Détroit 

#It will be always localhost
- hosts: localhost

  roles:

    # Start. has to be always enable 
    - logs
    # Stop. has to be always enable 

  # post_tasks:
  #   - file: path=/etc/udev/rules.d/70-persistent-net.rules state=absent
  #   - command: /sbin/shutdown -h now