---
- hosts: SystemPushInstall

  roles:
    - logs
    
    - set_custom_fact

    - role: tinc-static
      when: sync_log|bool == True

    - role: kalite 
      version: "{{ ansible_local.device_list.[device_name].kalite_version }}"
      lang: "{{ ansible_local.device_list.[device_name].kalite_lang }}"
      when: ansible_local.device_list[device_name].kalite is defined

    - role: mongodb
      when: ansible_local.device_list[device_name].mongodb is defined

    - role: mook
      mook_name: bsfcampus
      version: "{{ ansible_local.device_list.[device_name].bsfcampus_version }}"
      when: ansible_local.device_list[device_name].bsfcampus is defined

    - role: mook
      mook_name: koombookedu
      version: "{{ ansible_local.device_list.[device_name].koombookedu_version }}"
      when: ansible_local.device_list[device_name].koombookedu is defined

    - role: zim_install
      zim_name: "{{ ansible_local.device_list.[device_name].zim_install_name }}"
      when: ansible_local.device_list[device_name].zim_install is defined

    - role: ideascube
      version: "{{ ansible_local.device_list.[device_name].ideascube_version }}"
      when: ansible_local.device_list[device_name].ideascube is defined

    - role: idc_import
      content_name: "{{ ansible_local.device_list.[device_name].idc_import_content_name }}"
      when: ansible_local.device_list[device_name].idc_import is defined