---
# Ansible playbook for Coeur de forêt

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs

    #Uncomment to lunch an update
    # - role: upgradeIdc0.7.0
    #   version: "0.7.0-1"
    #   mook_name: ""