---
# Ansible playbook for BSF Campus

#It will be always localhost
- hosts: localhost
  vars:
    projectName: BsfCampus

  roles:
    # Start. has to be always enable 
    - role: firstStart
      timezone: "Africa/Dakar"
      ideascube_id: "{{ projectName }}"
      boxtype: koombook

    - logs
    # Stop. has to be always enable 

    # # Can be enable/disable on demand but affect all devices

    # - role: ideascube
    #   version: "0.4.0-1"
    #   ideascube_id: "{{ projectName }}"

    # - appinventor
    # #   when: ansible_hostname == 'KoomBook483'

    # # Update Mook plateform
    # - mongodb
    # - { role: mook, mook_name: bsfcampus }
    # - { role: mook, mook_name: fun }

    # Play a role for a specific device
    #- { role: iptables, when: ansible_hostname == 'KoomBook603' }
    #- { role: ideascube, when: ansible_hostname == 'KoomBook484' }

  # post_tasks:
  #   - command: /sbin/shutdown -h now