---
- hosts: localhost

  roles:
    # Enable or disable to suit your needs

    # This role automatically send logs to central server each time the device gets an Internet connection 
    - logs

    # - tinc-static

    - role: rename_device
      ideascube_id: "idb_fra_jeancarre"
      when: ansible_hostname == 'idb-fra-emmaus-924'

    - role: upgradeIdc
      version: "0.9.8"

    # - role: kalite
    #   version: "0.15.0"
    #   lang: "fr"

    # - role: zim_install
    #   zim_name: "wikipedia.fr wikipedia.fa wiktionary.fr wikiversity.fr wikisource.fr tedxgeneva2014.fr tedxlausanne2012.fr tedxlausanne2013.fr tedxlausanne2014.fr cest-pas-sorcier.fr gutenberg.fr"

    #- role: idc_import
    #  content_name: "12-Emmaus/Contenus/content.csv"
