---
# Ansible playbook for BSF CAMPUS RDC

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs

    - kalite

    - role: ideascube
      version: "0.5.0-1"

    - role: kiwix
      kiwixProject: wikipedia
      portProject: 8002
      version: ""

    # - mongodb
    - role: mook
      mook_name: bsfcampus