---
- hosts: localhost

  roles:
    # Enable or disable to suit your needs

    # This role automatically send logs to central server each time the device gets an Internet connection 
    - logs
    
    - mongodb

    - role: mook
      mook_name: bsfcampus

    - role: mook
      mook_name: koombookedu

    - role: zim_install
      zim_name: "wikipedia.fr cest-pas-sorcier.fr tedxgeneva2014.fr universcience-tv.fr tedxlausanne2012.fr tedxlausanne2013.fr tedxlausanne2014.fr"
