---
- hosts: localhost

  roles:
    # Enable or disable to suit your needs

    # This role automatically send logs to central server each time the device gets an Internet connection 
    - logs

    - tinc-static

    # - role: zim_install
    #   zim_name: "wikipedia.en gutenberg.en wiktionary.en tedbusiness.en teddesign.en tedentertainment.en tedglobalissues.en tedscience.en tedtechnology.en"

    # - role: kalite
    #   version: "0.15.0"
    #   lang: "en"