---
# Ansible playbook for LWB Détroit 

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs

    - role: upgradeIdc
      version: "0.9.0"

    - tinc-static
