---
# Ansible playbook for IFB 

#It will be always localhost
- hosts: localhost

  roles:
    # Has to be always enable
    - logs
    # - role: upgradeKb
    #   version: "0.4.1-1"

    # # #Uncomment to lunch an update
    # - role: updateIdeascube
    #   version: "0.5.0-1"
    #   ideascube_id: "kb_mooc_cog"

    # - role: mook
    #   mook_name: "mook"

    # - role: updateMook
    #   mook_name: "mook"