---
# Ansible playbook for Cdf

#It will be always localhost
- hosts: localhost
  roles:
    # Has to be always enable 
    # - role: firstStart
    #   timezone: Europe/Paris
    #   ideascube_id: Cdf

    - logs

    # Uncomment to lunch an update
    #- { role: ideascube, version: 0.4.0-1 }