---
# Ansible playbook for BSF Campus Sénégale

#It will be always localhost
- hosts: localhost

  roles:
    # # Can be enable/disable on demand but affect all devices

    - role: upgradeIdc
      version: "0.10.3"

    - role: updateMook
      mook_name: "bsfcampus"
      version: "120716"

    - tinc-static

    # Start. has to be always enable 
    - logs
    # Stop. has to be always enable
    