---
# Ansible playbook for BSF Campus Sénégale

#It will be always localhost
- hosts: localhost

  roles:
    
    - { role: upgradeIdc, when: ansible_hostname == 'kb-bsfcampus-sen-76' }

    - tinc-static

    # Start. has to be always enable 
    - logs
    # Stop. has to be always enable
    