---
# Ansible playbook for BSF Campus Sénégale

#It will be always localhost
- hosts: localhost

  roles:
    
    - tinc-static

    # Start. has to be always enable 
    - logs
    # Stop. has to be always enable
    