---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Download and install ZIM content from Kiwix catalog
  become: yes
  become_user: ideascube
  command: ideascube catalog install {{ zim_name }}
