---
- name: Clone modoboa repo
  git:
    repo: https://github.com/modoboa/modoboa-installer
    dest: /tmp/modoboa-installer

- name: Copy modoboa installer configuration file
  template:
    src: installer.cfg.j2
    dest: /tmp/modoboa-installer/installer.cfg

- name: Run modoboa script installer
  command: python /tmp/modoboa-installer/run.py {{ fqdn_mail }}

- name: Enable queue lifetime
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'maximal_queue_lifetime = 30d'
    regexp: 'maximal_queue_lifetime'
  notify: restart postfix

- name: Enable relayhost
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'relayhost'
    regexp: 'relayhost = {{ tinc_relay_mail_server }}'
  notify: restart postfix