---
- name: Clone modoboa repo
  git:
    repo: https://github.com/modoboa/modoboa-installer
    dest: ~/

- name: Copy modoboa installer configuration file
  template:
    src:   installer.cfg.j2
    dest:  ~/modoboa-installer/installer.cfg

- name: Run modoboa script installer
  command: ./run.py {{ fqdn_mail }}

- name: Enable queue lifetime
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'maximal_queue_lifetime = 30d'
    regexp: 'maximal_queue_lifetime'
  notify: restart postfix

- name: Enable relayhost
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'relayhost'
    regexp: 'relayhost = {{ tinc_relay_mail_server }}'
  notify: restart postfix