---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Create modoboa venv directory
  file: path=/srv/modoboa/env
    state=directory

- name: Upgrade setuptools
  pip: name=setuptools
    state=latest
    chdir=/srv/modoboa/
    virtualenv_command=/usr/bin/virtualenv
    virtualenv=/srv/modoboa/env
  when: (ansible_local.installed_software.software.modoboa | default (omit)) is undefined

- name: Clone modoboa repo
  git:
    repo: https://github.com/modoboa/modoboa-installer
    dest: /tmp/modoboa-installer
  when: (ansible_local.installed_software.software.modoboa | default (omit)) is undefined

- name: Copy modoboa installer configuration file
  template:
    src: installer.cfg.j2
    dest: /tmp/modoboa-installer/installer.cfg
  when: (ansible_local.installed_software.software.modoboa | default (omit)) is undefined

- name: Run modoboa script installer
  shell: yes | python /tmp/modoboa-installer/run.py --version={{modoboa_version}} {{ fqdn_mail }}
  args:
    chdir: /tmp/modoboa-installer/
  when: (ansible_local.installed_software.software.modoboa | default (omit)) is undefined

- name: Enable queue lifetime
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'maximal_queue_lifetime = 30d'
    regexp: 'maximal_queue_lifetime'
  notify: restart postfix

- name: Enable relayhost
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'relayhost = {{ ansible_local.device_list[generic_project_name].modoboa.tinc_relay_mail_server }}'
    regexp: 'relayhost'
  notify: restart postfix

- name: Change myhostname with mx_domain var
  lineinfile:
    dest: '/etc/postfix/main.cf'
    line: 'myhostname = {{ ansible_local.device_list[generic_project_name].modoboa.mx_domain }}'
    regexp: 'myhostname ='
  notify: restart postfix

- name: Flush postfix queue when target devices gets up
  lineinfile:
    dest: '/etc/tinc/email/host-up'
    line: 'sleep 10 && postqueue -f'
    regexp: 'sleep'
    create: yes
  notify: reload tinc
