---
- name: ensure custom facts directory exists
  file: >
    path=/etc/ansible/facts.d
    recurse=yes
    state=directory

- name: install custom fact module for device list
  copy: >
    src=device_list.fact
    dest=/etc/ansible/facts.d/device_list.fact
    mode=0666
  when: configure is undefined or configure == false

- set_fact: generic_project_name={{ ansible_hostname | regex_replace('-\d+', '') }}

- name: Device hostname
  debug: msg="{{ generic_project_name }}"

- name: reload ansible_local
  setup: filter=ansible_local