---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Open all outgoing connection to allow NFS, dirty but working ! 
  command: iptables -t filter -I OUTPUT -j ACCEPT

- name: Install nfs-common
  apt: name=nfs-common state=present

- name: Create a working dir for NFS shared
  file: path=/media/synology/ state=directory

- name: Mount shared folder from a NFS Share
  command: mount -t nfs -o proto=tcp,port=2049 192.168.1.2:"/volume1/Gestion des contenus" /media/synology
  
- name: Import data 
  become: yes
  become_user: ideascube
  shell: ideascube import_medias /media/synology/{{content_name}}

- name: Unmount shared folder from a NFS Share
  command: umount /media/synology