---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Copy stop_firewall.sh file
  copy: src=stop_firewall.sh dest=/tmp/stop_firewall.sh mode="u+x"

- name: Flush firewall to allow NFS
  command: /tmp/stop_firewall.sh

- name: Install nfs-common
  apt: name=nfs-common state=present

- name: Mount shared folder from a NFS Share
  mount: name=/home/ideascube/synology src="192.168.1.2:/volume1/Gestion\040des\040contenus" fstype=nfs opts=rsize=8192,wsize=8192,timeo=14,intr state=mounted
  
- name: Import data 
  become: yes
  become_user: ideascube
  shell: ideascube import_medias /home/ideascube/synology/{{content_name}}

- name: Unmount shared folder from a NFS Share
  mount: name=/home/ideascube/synology state=absent