---
- name: Stat on srv directory
  stat: path=/srv/
  register: srv_dir

- name: Remove /srv/ directory to link it to external HDD
  file: path=/srv/ state=absent
  when: srv_dir.stat.isdir is defined

- name: Symlink /srv/ to external HDD
  file: src={{samba_dir}} dest=/srv/ state=link
  when: srv_dir.stat.isdir is defined
