---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Install Samba packages
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "samba"
    - "samba-common"
    - "samba-common-bin"

- name: Create root Samba directories
  file:
    path: "{{ samba_dir }}"
    state: "directory"
    owner: "nobody"
    group: "nogroup"
    mode: "0751"

- name: Configure Samba
  template:
    src: "smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: [ "Check samba config" ]

- name: Test if a fex file exist, if yes, the device is an Olimex
  stat: path=/boot/bin/lime2.bin
  register: fex_file
  when: ansible_architecture == "armhf"
    or ansible_architecture == "armv7l"

- name: Test if a DTB Lime2 file exist (new olimex lime2 image)
  stat: path=/boot/dtb/sun7i-a20-olinuxino-lime2.dtb
  register: dtb_file
  when: ansible_architecture == "armhf"
    or ansible_architecture == "armv7l"

- include: lime2.yml
  when: (fex_file.stat.exists is defined and fex_file.stat.exists 
    or dtb_file.stat.exists is defined and dtb_file.stat.exists)
    and (ansible_architecture == "armhf" 
    or ansible_architecture == "armv7l")
    and sda1.stat.isblk == True

- name: Register Samba service
  service: name=samba-ad-dc enabled=yes
