- name: Clone/update mook api
  become: True
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/bsfcampus/mook-bsf-api.git 
    dest={{ mook_path }}/{{ mook_name }}/api
    accept_hostkey=yes 
    force=yes
    update=yes
    depth=1
  tags: ["custom","update"]

- name: Install specific packages
  apt: name={{ item }} state=latest
  with_items:
    - python-pip
    - python-dev
    - python-pkg-resources
    - unzip
    - libffi6
    - libffi-dev
    - uwsgi-plugin-python
  tags:
    - custom

- name: Install virtualenv
  pip: name=virtualenv extra_args="--no-cache-dir"
  tags:
    - custom

- name: Update setuptools
  pip: name=setuptools extra_args="-U"
  tags:
    - custom

- name: Create a static dir if we are using an external hard drive
  file: path=/media/hdd/{{ mook_name }}/static/tmp state=directory mode=0755 owner={{ username }} group={{ username }}
  when: (ansible_architecture == "armhf" or ansible_architecture == "armv7l")
    and ansible_devices.sda.partitions.sda1 is defined
  tags:
    - custom
    
- name: Create simlink if we are using an external hard drive
  file: src=/media/hdd/{{ mook_name }}/static dest={{ mook_path }}/{{ mook_name }}/static state=link
  when: (ansible_architecture == "armhf" or ansible_architecture == "armv7l")
    and ansible_devices.sda.partitions.sda1 is defined
  tags:
    - custom
    
- name: Create static dir
  file: path={{ mook_path }}/{{ mook_name }}/static/tmp state=directory owner={{username}} group={{username}} mode=0775
  when: ansible_architecture == "x86_64"
  tags:
    - custom
    
- name: Install python requierment
  pip: requirements=requirements.txt 
    chdir={{ mook_path }}/{{ mook_name }}/api 
    virtualenv_command=/usr/local/bin/virtualenv 
    virtualenv={{ mook_path }}/{{ mook_name }}/api/env
    extra_args="--no-cache-dir"
  tags:
    - custom
    
- name: Copy settings_local config files
  template: src=settings_local.py.j2 dest={{ mook_path }}/{{ mook_name }}/api/settings_local.py
  tags: ['custom','rename']

- name: Delete zero octet files
  shell: find ./ -empty -type f -delete chdir="{{ mook_path }}/{{ mook_name }}/static/"
  tags: 
    - update
    
- name: add conf for KoomBook
  lineinfile: dest={{ mook_path }}/{{ mook_name }}/api/settings_local.py 
    regexp='' 
    insertafter=EOF 
    line='    CENTRAL_SERVER_KEY = \"{{ ansible_hostname }}\" \n    CENTRAL_SERVER_SECRET = \"{{ ansible_machine_id }}\"' 
    owner={{username}} group={{username}} mode=755
  tags: ['custom','rename']
  ignore_errors: yes

- name: Add domain name for hotspot interface
  lineinfile: dest=/etc/hosts
    regexp='^{{hotspotip}}'
    line='{{hotspotip}} {{ idc_uniq_device_name |replace("_", "-") }}.lan {{ hostname }} {{ mook_front_server_name }}'
    state=present
  tags: ['custom','rename']
  ignore_errors: yes
    
- name: Setup startup file for uwsgi
  copy: src=settings_central.py dest={{ mook_path }}/{{ mook_name }}/api 
    owner={{username}} group={{username}} mode=755
  notify: restart mook-sync
  tags:
    - custom
    