- name: Clone mook front
  become: True
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/{{url_project_name}}/bsf-campus.git 
    dest={{ mook_path }}/{{ mook_name }}/front 
    accept_hostkey=yes 
    depth=1
  tags:
    - custom

- name: Change bitbucket owner repository
  replace: dest=/home/git
    regexp='gryzzlab'
    replace='bsfcampus'
  tags:
    - update

- name: Change repository name
  replace: dest=/home/git
    regexp='mook-bsf-front-end-backbone.git'
    replace='bsf-campus.git'
  tags:
    - update
    
- name: Update mook front
  become: True
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/{{url_project_name}}/bsf-campus.git 
    dest={{ mook_path }}/{{ mook_name }}/front 
    accept_hostkey=yes 
    update=yes 
    depth=1
  tags:
    - update
    
- name: Get and unarchive the vendor package
  become: True
  become_user: ideascube
  unarchive: src={{filer_bsf}}/vendor.zip dest={{ mook_path }}/{{ mook_name }}/front copy=no
  tags:
    - custom
    
- name: Copy config.js config files
  template: src=config.js.j2 dest={{ mook_path }}/{{ mook_name }}/front/config.js
  tags:
    - custom
    
- name: Fix rights
  file: path={{ mook_path }}/{{ mook_name }} state=directory owner={{ username }} group={{ username }} recurse=yes
  tags: [custom,update]