---
- include: pre_install.yml task=mook

- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Set mook project name to have the right URL
  set_fact: url_project_name="gryzzlab"
  when: mook_name == 'bsfcampus'

- name: Set mook project name to have the right URL
  set_fact: url_project_name="bsfcampus"
  when: mook_name == 'koombookedu'

- name: Set the central server variable for BSF Campus
  set_fact: central_server_host="http://api.bsfcampus.org/"
  when: mook_name == 'bsfcampus'

- name: Set the central server variable for KoomBook EDU
  set_fact: central_server_host="http://mook-api.bibliosansfrontieres.fr/"
  when: mook_name == 'koombookedu'

- include: back_end.yml
  when: ansible_local.installed_software.software.mook < "{{ version }}"

- include: front_end.yml
  when: ansible_local.installed_software.software.mook < "{{ version }}"

- include: system.yml
  when: ansible_local.installed_software.software.mook < "{{ version }}"

- include: post_install.yml task=mook version="{{ version }}"
  when: ansible_local.installed_software.software.mook < "{{ version }}"