---
- include: ../../../pre_install.yml task=mook

- include_vars: group_vars/{{ ansible_architecture }}.yml

# Set variables

- name: Set mook project name to have the right URL
  set_fact: url_project_name="gryzzlab"
  when: mook_name == 'bsfcampus'

- name: Set mook project name to have the right URL
  set_fact: url_project_name="bsfcampus"
  when: mook_name == 'koombookedu'

- name: Set the central server variable for BSF Campus
  set_fact: central_server_host="http://api.bsfcampus.org/"
  when: mook_name == 'bsfcampus'

- name: Set the central server variable for KoomBook EDU
  set_fact: central_server_host="http://mook-api.bibliosansfrontieres.fr/"
  when: mook_name == 'koombookedu'

# Call those roles if this is the first install

- include: back_end.yml
  when: ansible_local.installed_software.software.mook_name|int == 0

- include: front_end.yml
  when: ansible_local.installed_software.software.mook_name|int == 0

- include: system.yml
  when: ansible_local.installed_software.software.mook_name|int == 0

# Call those roles if the Mook has to be upgraded 

- include: upgrade_mook_100516.yml
  when: ansible_local.installed_software.software.mook_name|int < "{{ version }}"
    and ansible_local.installed_software.software.mook_name|int != 0
  ignore_error: yes

- include: ../../../post_install.yml task=mook_name version="{{ version }}"
  when: ansible_local.installed_software.software.mook_name|int < "{{ version }}"
    or ansible_local.installed_software.software.mook_name|int == 0