---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Set the central server variable
  set_fact: central_server_host="http://api.bsfcampus.org/"

- name: Install uwsgi
  apt: name={{ item }} state=present
  with_items:
  - uwsgi
  - uwsgi-plugin-python

####
# BACK END CONFIGURATION
####
- name: Clone mook api
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/gryzzlab/mook-bsf-api.git dest={{ mook_path }}/{{ mook_name }}/api accept_hostkey=yes update=yes depth=1

####
# FRONT END CONFIGURATION
####
- name: Clone mook front
  become_user: ideascube
  git: repo=ssh://git@altssh.bitbucket.org:443/gryzzlab/mook-bsf-front-end-backbone.git dest={{ mook_path }}/{{ mook_name }}/front accept_hostkey=yes update=yes depth=1

- name: Delete old way of synching 
  lineinfile: dest=/etc/rc.local state=absent regexp='su ideascube -c'

####
# MongoDB
####
- name: Disable service mongodb
  service: name=mongodb enabled=no

- name: Delete sysvinit file
  file: path=/etc/init.d/mongodb state=absent

- name: Copy mongodb repair script
  copy: src=mongo_repair.sh dest=/opt/mongo/mongo_repair.sh mode=755

- name: Fix rights on log dir
  file: path=/var/log/mongodb/ state=directory owner=mongodb group=nogroup recurse=yes

- name: Setup startup file
  copy: src=mongodb.service dest=/etc/systemd/system/mongodb.service owner=root group=root

- name: Enable service mongodb
  service: name=mongodb enabled=yes

- name: Copy new uwsgi startup file. Uwsgi must start after MongoDB
  copy: src=uwsgi.service dest=/etc/systemd/system/uwsgi.service owner=root group=root

####
# Systemd startup script
####
- name: Copy template for systemd mook-sync
  template: src=mook-sync.service.j2 dest=/etc/systemd/system/mook-sync.service

- name: Enable service mook-sync
  service: name=mook-sync enabled=yes
  notify: restart uwsgi