- name: Add hdparm to save energy
  lineinfile: dest=/etc/hdparm.conf
              regexp=''
              insertafter=EOF
              line='/dev/sda {
                      spindown_time = 280
              }'
  tags: 
    - master

- name: fake-hwclock conf for ARM system 
  copy: content="FORCE=force" dest=/etc/default/fake-hwclock
  tags: 
    - mastercustom

- name: Ensure the HDD mountpoint exists
  file: path=/media/hdd state=directory
  tags: 
    - custom

- stat: path=/dev/sda1
  register: dev_sda
  tags: 
    - custom

- name: Mount /dev/sda1
  mount: name=/media/hdd/ src=/dev/sda1 fstype=ext4 state=mounted opts=noatime,nofail
  when: dev_sda.stat.exists == True
  tags: 
    - custom

- name: Mount /dev/sda
  mount: name=/media/hdd/ src=/dev/sda fstype=ext4 state=mounted opts=noatime,nofail
  when: dev_sda.stat.exists == False
  ignore_errors: yes
  tags: 
    - custom

- name: Copy fex.file
  template: src=lime2.fex.j2 dest=/boot/bin/lime2.fex
  tags: 
    - custom

- name: Build binary from fex
  shell: sunxi-fexc lime2.fex > lime2.bin chdir=/boot/bin/
  tags: 
    - custom

- name: Copy patch U-Boot package
  get_url: url={{filer_bsf}}/linux-u-boot-next-lime2_5.14_armhf.deb
    dest=/tmp/linuxUboot.deb owner=root group=root mode=755
  tags: 
    - custom

- name: install patch U-Boot package
  apt:  deb=/tmp/linuxUboot.deb
  tags: 
    - custom