---
- name: fake-hwclock conf for ARM system 
  copy: content="FORCE=force" dest=/etc/default/fake-hwclock

- name: Ensure the HDD mountpoint exists
  file: path=/media/hdd state=directory

- stat: path=/dev/sda1
  register: dev_sda

- name: Mount /dev/sda1
  mount: name=/media/hdd/ src=/dev/sda1 fstype=ext4 state=mounted opts=noatime,nofail
  when: dev_sda.stat.exists == True

- name: Mount /dev/sda
  mount: name=/media/hdd/ src=/dev/sda fstype=ext4 state=mounted opts=noatime,nofail
  when: dev_sda.stat.exists == False
  ignore_errors: yes

- name: Convert DTB file to DTS
  command: dtc -I dtb -O dts /boot/dtb/sun7i-a20-olinuxino-lime2.dtb -o /boot/dtb/sun7i-a20-olinuxino-lime2.dts

- name: Change the PIN for the LED and Activate heartbeat mode
  replace: dest=/boot/dtb/sun7i-a20-olinuxino-lime2.dts
    regexp='gpios = <0x1e 0x7 0x2 0x0>;' 
    replace='gpios = <0x1e 0x7 0x14 0x0>;\n                        linux,default-trigger = "heartbeat";'

- name: Convert DTS file to DTB
  command: dtc -I dts -O dtb /boot/dtb/sun7i-a20-olinuxino-lime2.dts -o /boot/dtb/sun7i-a20-olinuxino-lime2.dtb