---
- name: Get startup file list
  shell: grep kiwix-serve /etc/init.d/* | cut -d "/" -f4 | cut -d ":" -f1
  register: startup_file_list 

- debug: msg="{{ startup_file_list }}"

- name: Stop running kiwix service
  command: /etc/init.d/{{ item }} stop
  with_items: "{{ startup_file_list.stdout_lines }}"

- name: Disable init file for kiwix project
  command: update-rc.d {{ item }} disable
  with_items: "{{ startup_file_list.stdout_lines }}"

- name: Disable Nginx virtual host for kiwix project
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: "{{ startup_file_list.stdout_lines }}"

- name: create Kiwix directory 
  file: path={{zim_path}}/data/content/ state=directory

- name: Copy create_zim_archive.sh file
  copy: src=create_zim_archive.sh /tmp/create_zim_archive.sh

- name: Create an archive from available zim
  command: create_zim_archive.sh

- name: Add a temporary remote to install the zim archive with ideascube catalog
  command: ideascube catalog remotes add "Temporary catalog" "Temporary catalog" "{{old_kiwix_path}}/catalog.yml"

- name: Get a list of zim archive to install 
  command: grep "local_" {{old_kiwix_path}}/catalog.yml
  register: zim_file_to_add

- name: Install zim file with ideascube catalog 
  command: ideascube catalog install {{item}}
  with_items: "{{ zim_file_to_add }}"

# - name: Remove empty folder 
#   shell: find {{ old_kiwix_path }} -type d -empty -delete