---
- include_vars: group_vars/{{ ansible_architecture }}.yml
  tags: ['master', 'update']
  
- name: Copying kiwix binaries
  get_url: url={{filer_bsf}}/kiwix-serve-{{ ansible_architecture }} dest=/usr/local/bin/kiwix-serve mode=755 timeout=20
  tags: 
    - master

- name: Create a kiwix directory in ideascube folder
  file: path={{zim_path}}/ owner={{username}} group={{username}} state=directory
  tags: 
    - master

- name: Setup startup file
  template: src=kiwix-server.service.j2 dest=/etc/systemd/system/kiwix-server.service
  tags: 
    - master

- name: Copy nginx vhost
  template: src=nginx.vhost.j2 dest=/etc/nginx/sites-available/kiwix
  tags: 
    - master

- name: Install Kiwix catalogs
  become: yes
  become_user: ideascube
  command: ideascube catalog remotes add "{{ item.name }}" "{{ item.description }}" "{{ item.url }}"
  with_items:
  - name: "Kiwix"
    description: "Kiwix ZIM content"
    url: http://catalog.ideascube.org/kiwix.yml
  - name: "OSMybon"
    description: "Experimental OSM Maps catalog"
    url: http://catalog.yohanboniface.me/catalog.yml
  tags: 
    - custom
    
- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kiwix dest=/etc/nginx/sites-enabled/kiwix state=link
  notify: restart nginx
  tags: 
    - master

- name: Enable service kiwix
  service: name=kiwix-server enabled=yes
  notify: restart kiwix
  tags: 
    - master

- shell: systemctl is-enabled wikipedia ; echo
  register: startup_file
  tags: 
    - update
    
- include: dust-removal-{{ ansible_architecture }}.yml
  tags: 
    - update