---
- include_vars: group_vars/{{ ansible_architecture }}.yml
  tags: 
    - master
  
- name: Copying kiwix binaries
  get_url: url={{filer_bsf}}/kiwix-serve-{{ ansible_architecture }} dest=/usr/local/bin/kiwix-serve mode=755 timeout=20
  tags: 
    - master

- name: Create a kiwix directory in ideascube folder
  file: path={{zim_path}}/ state=directory
  tags: 
    - master

- name: Setup startup file
  template: src=kiwix-server.service.j2 dest=/etc/systemd/system/kiwix-server.service
  tags: 
    - master

- name: Copy nginx vhost
  template: src=nginx.vhost.j2 dest=/etc/nginx/sites-available/kiwix
  tags: 
    - master

- name: Check if Kiwix catalog exist
  stat: path=/var/cache/ideascube/catalog/remotes/Kiwix.yml
  when: ansible_architecture == "x86_64"
  register: st
  tags: 
    - master

- name: Check if Kiwix catalog exist
  stat: path=/var/ideascube/catalog/remotes/Kiwix.yml
  when: (ansible_architecture == "armhf" or ansible_architecture == "armv7l")
  register: st
  tags: 
    - master

- name: Install Kiwix catalog
  become: yes
  become_user: ideascube
  command: ideascube catalog remotes add "Kiwix" "Kiwix ZIM content" http://catalog.ideascube.org/kiwix.yml
  when: st.stat.exists == False
  tags: 
    - master
    
- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kiwix dest=/etc/nginx/sites-enabled/kiwix state=link
  notify: restart nginx
  tags: 
    - master

- name: Enable service kiwix
  service: name=kiwix-server enabled=yes
  notify: restart kiwix
  tags: 
    - master