---
- include: ../../../pre_install.yml task=kiwix

- include: kiwix.yml
  when: ansible_local.installed_software.software.kiwix == "0"

- include: ../../../post_install.yml task=kiwix task_version="{{ kiwix_version }}"
  when: ansible_local.installed_software.software.kiwix == "0"