---
- stat: path=/usr/local/bin/kiwix-serve
  register: st

- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Copying kiwix-server binary {{ kiwixProject }} for ARM
  get_url: url={{filer_bsf}}/kiwix-serve-ARM dest=/usr/local/bin/kiwix-serve mode=755
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and st.stat.exists == False

- name: Copying kiwix-manage binary {{ kiwixProject }} for ARM
  get_url: url={{filer_bsf}}/kiwix-manage-ARM dest=/usr/local/bin/kiwix-manage mode=755
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and st.stat.exists == False

- name: Copying kiwix-server binary {{ kiwixProject }} for amd64
  get_url: url={{filer_bsf}}/kiwix-serve-AMD64 dest=/usr/local/bin/kiwix-serve mode=755
  when: ansible_architecture == 'x86_64' and st.stat.exists == False

- name: Copying kiwix-manage binary {{ kiwixProject }} for amd64
  get_url: url={{filer_bsf}}/kiwix-manage-AMD64 dest=/usr/local/bin/kiwix-manage mode=755
  when: ansible_architecture == 'x86_64' and st.stat.exists == False

- name: Create a library directory if not exist
  file: path={{zim_path}} state=directory
  when: st.stat.exists == False

# Test if the conf file already exist on the device otherwhise skip...
- stat: path=/etc/nginx/sites-available/{{ kiwixProject }}
  register: confFile

- name: Setup startup file for {{ kiwixProject }}
  template: src=kiwix.j2 dest=/etc/init.d/{{ kiwixProject }} owner=root group=root mode=755
  when: confFile.stat.exists == False

- name: Copy nginx vhost for {{ kiwixProject }}
  template: src=nginx.vhost.j2 dest=/etc/nginx/sites-available/{{ kiwixProject }}
  when: confFile.stat.exists == False

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/{{ kiwixProject }} dest=/etc/nginx/sites-enabled/{{ kiwixProject }} state=link
  when: confFile.stat.exists == False
  notify: restart nginx

- name: Create a {{ kiwixProject }} directory to store ZIM file
  file: path={{zim_path}}/{{ kiwixProject }} state=directory
  when: confFile.stat.exists == False

- name: Download {{ kiwixProject }} zim file 
  get_url: url=http://download.kiwix.org/zim/{{ kiwixProject }}/{{ item }} dest={{zim_path}}/{{ kiwixProject }} timeout=20
  command: kiwix-manage {{zim_path}}/{{ kiwixProject }}/library.xml add {{zim_path}}/{{ kiwixProject }}/{{ item }}
  with_items: "{{version}}"
  ignore_errors: yes
  when: download_data|bool == True and confFile.stat.exists == False

- name: Enable service kiwix for {{ kiwixProject }}
  service: name={{ kiwixProject }} enabled=yes
  when: confFile.stat.exists == False

- tasks:
  include: ../../../post_tasks.yml task={{ kiwixProject }} version=1
  when: confFile.stat.exists == False
