---
- include: ../../../pre_install.yml task=kiwix
  tags: [master,custom,update]
  
- include: kiwix.yml

- include: ../../../post_install.yml task=kiwix task_version="{{ kiwix_version }}"
  when: ansible_local.installed_software.software.kiwix == "0"
  tags: [master,custom,update]
