---
- name: restart nginx
  service: name=nginx state=restarted

- name: restart uwsgi
  service: name=uwsgi state=restarted

- name: restart mook-sync
  service: name=mook-sync-{{ mook_name }} state=restarted