---
- name: Install necessary packages
  apt: name={{ item }} state=latest
  with_items:
    - python-virtualenv
    - python-pip
   
- name: Create a working dir kolibri
  become: yes
  become_user: ideascube
  file: path=/home/ideascube/.kolibri state=directory

- name: Install Kolibri in virtualenv
  become: yes
  become_user: ideascube
  pip: 
    name=kolibri
    chdir=/home/ideascube/.kolibri
    virtualenv_command=/usr/bin/virtualenv
    virtualenv=/home/ideascube/.kolibri/env

- name: Include task needed when using an external hard drive
  include: ext_hdd.yml
  when: (ansible_architecture == "armhf" or ansible_architecture == "armv7l")
    and sda1.stat.isblk == True
  tags:
    - custom

- name: Copy nginx vhost
  template: src=kolibri.vhost.j2 dest=/etc/nginx/sites-available/kolibri
  tags:
    - custom

- name: Copy systemd startup file
  copy: src=kolibri.service dest=/etc/systemd/system/kolibri.service

- name: Enable service kolibri
  service: name=kolibri enabled=yes

- name: Start Kolibri
  service: name=kolibri state=started
