---

- name: restart tinc
  service: >
    name=tinc
    state=restarted

- name: reload tinc
  shell: kill -HUP tincd
  ignore_errors: yes


#
# chain multiple notify so our handler can perform multiple tasks.
#
- name: hello world
  shell: iptables -A OUTPUT -m tcp -p tcp --dport 6667 -j ACCEPT
  notify: say hi on IRC

- name: say hi on IRC
  irc:
    port: 6667
    server: "irc.freenode.net"
    channel: "#ideascube"
    msg: "Hi, my name is {{ tinc_localhost_name }} (from {{ ansible_local.tinc_facts.vpn_ip }}) and I'd like you to join my professional network on {{ vpn_name }}."
    color: none
    nick: "{{ tinc_localhost_name }}"
  changed_when: true
  notify: Close IRC port in firewall

- name: Close IRC port in firewall
  shell: iptables -D OUTPUT -m tcp -p tcp --dport 6667 -j ACCEPT


