---
- name: Install libffi-dev needed by Ansible 2.0
  apt: name=libffi-dev state=latest

- name: Fix broken PIP, ignore if requests folder does not exist
  command: mv /usr/local/lib/python2.7/dist-packages/requests /usr/local/lib/python2.7/dist-packages/requests.old/
  ignore_errors: yes

- name: Upgrade Pip & Ansible
  pip: name={{item}} state=latest
  with_items:
    - pip
    - ansible

- name: ensure custom facts directory exists
  file: >
    path=/etc/ansible/facts.d
    recurse=yes
    state=directory

- name: Get ideascube version
  shell: dpkg-query -W  ideascube  | awk '{print $2}' ; echo
  register: ideascube_version

- name: Save Ideascube version number
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
            section=software
            option=ideascube
            value={{ ideascube_version.stdout }}

- name: Get kalite version
  shell: kalite --version ; echo
  register: kalite_version

- name: Save kalite version number
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
            section=software
            option=kalite
            value={{ kalite_version.stdout }}

- name: Register if the device is managed by BSF or not
  ini_file: dest=/etc/ansible/facts.d/installed_software.fact
    section=management
    option=managed_by_bsf
    value={{ sync_log }}

- name: Create entry to clone/pull git repository
  copy: src=../../network-manager/files/nm-dispatcher dest=/etc/NetworkManager/dispatcher.d/ansiblePullUpdate
    owner=root group=root mode=0755 backup=yes force=yes

- name: remove old way of lunching ansible-pull
  file: path=/etc/dhcp/dhclient-exit-hooks.d/ansiblePullUpdate state=absent

- name: Reboot device to switch to new branch
  command: shutdown -r now