---
- name: Checkout staticfiles.json file size
  stat: path=/var/ideascube/static/staticfiles.json
  register: ideascube_staticfiles
  tags:
    - update

- name: Delete staticfiles.json file if size is null
  file: path=/var/ideascube/static/staticfiles.json state=absent
  when: ideascube_staticfiles.stat.size is defined
    and ideascube_staticfiles.stat.size == 0
  notify: restart uwsgi
  tags:
    - update

- name: Enable cards on homepage for ideascube upgrading from < 0.13.0
  become: yes
  become_user: ideascube
  command: ideascube reset_home
  when: ideascube_installed | version_compare('0.13.0', '<')
    and is_upgraded.changed == True
  tags:
    - update

# Add settings and conf
- name: Check if configuration file exist for Ideascube
  stat: path=/opt/venvs/ideascube/lib/python3.4/site-packages/ideascube/conf/{{ generic_project_name |replace("-", "_") }}.py
  register: conf_file
  tags: ['custom','rename','update']

- name: Set IDEASCUBE_ID variable
  set_fact: ideascube_id={{ generic_project_name |replace("-", "_") }}
  when: conf_file.stat.exists == True
  tags:
    - update

- name: Set IDEASCUBE_ID variable
  set_fact: ideascube_id={{ ideascube_project_name }}
  when: conf_file.stat.exists == True
  tags: ['custom','rename']

- name: Set IDEASCUBE_ID variable for koombook
  set_fact: ideascube_id=kb
  when: (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l')
    and conf_file.stat.exists == False
  tags: ['custom','rename','update']

- name: Set IDEASCUBE_ID variable for ideasbox
  set_fact: ideascube_id=idb
  when: (ansible_architecture == 'x86_64' or ansible_architecture == 'i386') and conf_file.stat.exists == False
  tags: ['custom','rename','update']

- name: Change IDEASCUBE_ID
  lineinfile: dest=/etc/default/ideascube
              regexp='IDEASCUBE_ID='
              line='IDEASCUBE_ID={{ ideascube_id }}'
              state=present
  notify: restart uwsgi
  tags: ['custom','rename','update']
