---
- include: ../../../pre_install.yml task=ideascube

- include: ideascube.yml
  when: ansible_local.installed_software.software.ideascube|int == 0

- include: upgrade_ideascube_0.9.3.yml
  when: ansible_local.installed_software.software.ideascube|int < "{{ version }}"
    and ansible_local.installed_software.software.ideascube|int != 0
  ignore_error: yes

- include: ../../../post_install.yml task=ideascube version="{{ version }}"
  when: ansible_local.installed_software.software.ideascube|int < "{{ version }}"
    or ansible_local.installed_software.software.ideascube|int == 0  