---
- include: branding.yml
  tags: ['custom','update']

- include: common_pre.yml

- include: {{ideascube_package_name}}.yml

- include: common_post.yml

- include: ../../../post_install.yml task={{ideascube_package_name}} task_version="{{ ideascube_newversion.stdout }}"
  tags: ['custom', 'update']
