---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Test if package is already installed 
  shell: dpkg-query -W  ideascube  | awk '{print $2}' ; echo
  register: ideascube_version

- debug: msg="installed ideascube version {{ ideascube_version.stdout }}"

- name: Set up the custom Policy Kit actions
  copy: src=org.bsf.ideascube.policy dest=/usr/share/polkit-1/actions/org.bsf.ideascube.policy 
    owner=root group=root mode=644
  when: ideascube_version.stdout == ""

- name: Set up the Policy Kit authorizations
  copy: src={{ item }} dest=/var/lib/polkit-1/localauthority/20-org.d/{{ item }} owner=root group=root mode=644
  with_items:
  - ideascube-networkmanager.pkla
  - ideascube-systemd.pkla
  ignore_errors: yes
  when: ideascube_version.stdout == ""

- name: Add the PAM service
  copy: src=ideascube.pam dest=/etc/pam.d/ideascube owner=root group=root mode=644
  when: ideascube_version.stdout == ""

# For ARM

- name: Create storage dir for ideascube
  file: path=/media/hdd/ideascube/storage/main state=directory owner={{ username }} group={{ username }}
  become: yes
  become_user: ideascube
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l' and ideascube_version.stdout == ""

- name: Copy ideascube package
  get_url: url={{filer_bsf}}/ideascube_{{ version }}_armhf.deb dest=/tmp/ideascube_{{ version }}_armhf.deb owner=root group=root mode=755
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and ideascube_version.stdout < "{{ version }}"

- name: install ideascube package
  apt: deb=/tmp/ideascube_{{ version }}_armhf.deb state=present
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" and ideascube_version.stdout < "{{ version }}"

# For AMD64

- name: Copy ideascube package
  get_url: url={{filer_bsf}}/ideascube_{{ version }}_amd64.deb dest=/tmp/ideascube_{{ version }}_amd64.deb owner=root group=root mode=755
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

- name: install ideascube package
  apt: deb=/tmp/ideascube_{{ version }}_amd64.deb state=present
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

# Should be already packaged !!!
- name: install missing dev package
  apt: name={{ item }} state=latest
  with_items:
   - libjpeg-dev
   - zlib1g-dev
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

- name: Workaround -> Remove Pillow and PIL
  file: path=/usr/lib/python2.7/dist-packages/PIL/ state=absent
  file: path=/usr/local/lib/python2.7/dist-packages/PIL state=absent
  file: path=/usr/lib/python2.7/dist-packages/PILcompat/ state=absent 
  file: path=/usr/lib/python2.7/dist-packages/Pillow-2.6.1.egg-info state=absent
  file: path=/usr/share/python/ideascube/lib/python2.7/site-packages/Pillow-3.0.0.egg-info state=absent
  file: path=/usr/share/python/ideascube/lib/python2.7/site-packages/PIL/ state=absent
  ignore_errors: yes
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"  

# Should be already packaged !!!
- name: Install Pillow
  pip: name=Pillow
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

- name: Move Pillow and PILL to ideascube venv
  command: mv /usr/local/lib/python2.7/dist-packages/PIL/ /usr/share/python/ideascube/lib/python2.7/site-packages/
  command: mv /usr/local/lib/python2.7/dist-packages/Pillow-3.0.0.egg-info/ /usr/share/python/ideascube/lib/python2.7/site-packages/
  ignore_errors: yes
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

- name: Workaround -> Remove Pillow and PIL
  file: path=/usr/lib/python2.7/dist-packages/PILcompat/ state=absent
  file: path=/usr/lib/python2.7/dist-packages/PIL/ state=absent
  file: path=/usr/local/lib/python2.7/dist-packages/PIL/ state=absent
  file: path=/usr/local/lib/python2.7/dist-packages/Pillow-3.0.0.egg-info state=absent
  ignore_errors: yes
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"  

- name: Ideascube migrate data after Pillow re-install
  become: yes
  become_user: ideascube
  shell: ideascube migrate
  notify: restart uwsgi
  when: ansible_architecture == 'x86_64' and ideascube_version.stdout < "{{ version }}"

# Add settings and conf

- name: Fix rights
  file: path=/var/ideascube/ state=directory owner={{ username }} group={{ username }} recurse=yes
  when: ideascube_version.stdout == ""

- name: Adapt STORAGE_ROOT for Nginx
  replace: dest=/etc/nginx/sites-available/ideascube regexp='/var/ideascube/main/media/' replace='/media/hdd/ideascube/storage/main/media/' backup=yes
  when: use_hdd|bool == True  and ideascube_version.stdout == ""

- name: Adapt STORAGE_ROOT for Nginx
  replace: dest=/etc/nginx/sites-available/ideascube regexp='/var/ideascube/static/' replace='/media/hdd/ideascube/storage/static/' backup=yes
  when: use_hdd|bool == True and ideascube_version.stdout == ""

- name: Add IDEASCUBE_ID
  lineinfile: dest=/etc/default/ideascube
              regexp='^'
              line='IDEASCUBE_ID={{ ideascube_id }}'
              state=present
  when: ideascube_version.stdout == ""

- lineinfile: dest=/etc/nginx/sites-available/ideascube regexp='443' state=absent
  notify: restart nginx
  when: ideascube_version.stdout == ""

- name: Create simLink
  file: src=/etc/uwsgi/apps-available/ideascube.ini dest=/etc/uwsgi/apps-enabled/ideascube.ini state=link
  when: ideascube_version.stdout == ""

- name: Ideascube collectstatic to the hard drive
  become: yes
  become_user: ideascube
  shell: ideascube collectstatic --noinput
  when: use_hdd|bool == True and ideascube_version.stdout == ""

- name: Ideascube migrate data to the hard drive
  become: yes
  become_user: ideascube
  shell: ideascube migrate
  notify: restart uwsgi
  when: use_hdd|bool and ideascube_version.stdout == ""

- name: Download CSV to import
  get_url: url={{filer_bsf}}/KB_Liste_contenus_videos+fiches.csv dest=/media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv
  when: ideascube_version.stdout == "" and import_ideascube_data|bool and use_hdd|bool

- name: Import data 
  become: yes
  become_user: ideascube
  shell: ideascube import_medias /media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv
  when: ideascube_version.stdout == "" and import_ideascube_data|bool and use_hdd|bool

- tasks:
  include: ../../../post_tasks.yml task=ideascube version={{ version }}
  when: ideascube_version.stdout < "{{ version }}"
