---
- include: ../../../pre_install.yml task=ideascube

- include: ideascube.yml
  when: ansible_local.installed_software.software.ideascube == "0"

- include: upgrade.yml
  when: ansible_local.installed_software.software.ideascube | version_compare('{{ ideascube_version }}', '<')
    and ansible_local.installed_software.software.ideascube != "0"

- include: ../../../post_install.yml task=ideascube task_version="{{ ideascube_version }}"
  when: ansible_local.installed_software.software.ideascube | version_compare('{{ ideascube_version }}', '<')
    or ansible_local.installed_software.software.ideascube == "0"