---
- include: pre_install.yml task=ideascube

- include: ideascube.yml
  when: ansible_local.installed_software.software.ideascube < "{{ version }}"

- include: post_install.yml task=ideascube version="{{ version }}"
  when: ansible_local.installed_software.software.ideascube < "{{ version }}"