---
- include: ../../../pre_install.yml task=ideascube

- include: ideascube.yml
  when: ansible_local.installed_software.software.ideascube = 0

- include: upgrade_ideascube_{{ version }}.yml
  when: ansible_local.installed_software.software.ideascube < "{{ version }}"
    and ansible_local.installed_software.software.ideascube != 0
  ignore_error: yes

- include: post_install.yml task=ideascube version="{{ version }}"
  when: ansible_local.installed_software.software.ideascube < "{{ version }}"
    or ansible_local.installed_software.software.ideascube = 0  