---
- name: Install uwsgi
  pip: name=uwsgi

- name: Create log dir for uwsgi
  file: path=/var/log/uwsgi state=directory owner=www-data group=www-data mode=0751

- name: Setup startup file for uwsgi
  copy: src=uwsgi dest=/etc/init.d/uwsgi owner=root group=root mode=755

- name: Create apps-enabled dir for uwsgi
  file: path=/etc/uwsgi/apps-enabled state=directory owner=www-data group=www-data mode=0751

# For ARM

- name: Create storage dir for ideascube
  file: path=/media/hdd/ideascube/storage state=directory owner={{ username }} group={{ username }}
  when: ansible_architecture == 'armhf' or ansible_architecture == 'armv7l'

- name: Copy ideascube package
  get_url: url={{filer_bsf}}/ideascube_{{ version }}_armhf.deb dest=/tmp/ideascube_{{ version }}_armhf.deb owner=root group=root mode=755
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

- name: install ideascube package
  become_user: ideascube
  apt: deb=/tmp/ideascube_{{ version }}_armhf.deb
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

# For AMD64

- name: Copy ideascube package
  get_url: url={{filer_bsf}}/ideascube_{{ version }}_amd64.deb dest=/tmp/ideascube_{{ version }}_amd64.deb owner=root group=root mode=755
  when: ansible_architecture == 'x86_64'

- name: install ideascube package
  become_user: ideascube
  apt: deb=/tmp/ideascube_{{ version }}_amd64.deb
  when: ansible_architecture == 'x86_64'

- name: Fix rights
  file: path=/var/ideascube/ state=directory owner=www-data group={{ username }} recurse=yes

- name: Add IDEASCUBE_ID
  lineinfile: dest=/etc/default/ideascube
              regexp='^'
              line='IDEASCUBE_ID={{ ideascube_id }}'
              state=present

- lineinfile: dest=/etc/nginx/sites-available/ideascube regexp='443' state=absent
  notify: restart nginx

- name: Create simLink
  file: src=/etc/uwsgi/apps-available/ideascube.ini dest=/etc/uwsgi/apps-enabled/ideascube.ini state=link

- name: Enable service uwsgi
  service: name=uwsgi enabled=yes

- name: Download CSV to import
  get_url: url={{filer_bsf}}/KB_Liste_contenus_videos+fiches.csv dest=/media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv

- name: Import data 
  shell: ideascube import_medias /media/hdd/IdeasServerContent/videos/KB_Liste_contenus_videos+fiches.csv

- tasks:
  include: ../../../post_tasks.yml task=ideascube version={{ version }}

  ajouter lien symbolic 