---
- include: ../../../pre_install.yml task=ideascube
  tags: ['master','custom', 'update']

- include: ideascube.yml

- include: ../../../post_install.yml task=ideascube task_version="{{ ideascube_version }}"
  tags: ['master','custom', 'update']
