---
- include: branding.yml
  tags: ['custom','update']

- include: ideascube.yml

- include: ../../../post_install.yml task=ideascube task_version="{{ ideascube_version }}"
  tags: ['custom', 'update']
