---
- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Remove uwsgi installed using pip (bug #17)
  pip: name=uwsgi state=absent executable=pip3
  tags: 
    - "0.9.3"

- name: Move uwsgi_params to the new storage folder
  command: mv -f /var/ideascube/uwsgi_params /media/hdd/ideascube/storage
  when: ansible_mounts["device"] == "/dev/sda1" and ansible_mounts["device"] == "/dev/mmcblk0/
  ignore_errors: yes
  tags: 
    - "0.9.3"

- name: Backup old ideascube var dir
  command: mv -f /var/ideascube/ /var/old_ideascube
  when: ansible_mounts["device"] == "/dev/sda1" and ansible_mounts["device"] == "/dev/mmcblk0/
  ignore_errors: yes
  tags: 
    - "0.9.3"

- name: Create a simlink to the HDD for the KoomBook
  file: src=/media/hdd/ideascube/storage dest=/var/ideascube state=link owner={{ username }} group={{ username }}
  when: ansible_mounts["device"] == "/dev/sda1" and ansible_mounts["device"] == "/dev/mmcblk0/
  tags: 
    - "0.9.3"

- name: Install uwsgi
  apt: name={{ item }} state=present
  with_items:
  - uwsgi
  - uwsgi-plugin-python3
  tags: 
    - "0.9.3"

- name: Configure the ideascube package repository
  template: src=ideascube.list.j2 dest=/etc/apt/sources.list.d/ideascube.list owner=root group=root mode=644
  tags: 
    - "0.9.3"

- name: Install ideascube dependencies
  apt: name=python3-minimal state=present
  tags: 
    - "0.9.3"

- name: Allow unauthenticated packages
  lineinfile: dest=/etc/apt/apt.conf.d/9999IDEASCUBEISABADBADBOY line='APT::Get::AllowUnauthenticated "true";' create=yes
  tags: 
    - "0.9.3"

- name: Install the ideascube package
  apt: name=ideascube={{ version }} state=present update_cache=yes force=yes
  tags: 
    - "0.9.3"

- name: Remove the unauthenticated hack
  file: path=/etc/apt/apt.conf.d/9999IDEASCUBEISABADBADBOY state=absent
  tags: 
    - "0.9.3"

- name: Remove linsting on 443 because the port is alredy used by sslh
  lineinfile: dest=/etc/nginx/sites-available/ideascube regexp='443' state=absent
  notify: restart nginx
  ignore_errors: yes
  tags: 
    - "0.9.3"

- name: Setup startup file for uwsgi
  copy: src=uwsgi.service dest=/etc/systemd/system/uwsgi.service owner=root group=root mode=644
  tags: 
    - "0.9.3"

- name: Enable service uwsgi
  service: name=uwsgi enabled=yes
  tags: 
    - "0.9.3"

- name: Lookup for the Ideascube device name
  set_fact: ideascube_device_name={{ ansible_hostname | regex_replace('_\d+', '') | replace("-", "_") }}
  tags: 
    - "0.9.3"

- name: Lookup for the Ideascube device name and number. ideascube_project_name must contain _ instead of - in the name 
  set_fact: ideascube_project_name={{ ansible_hostname | replace("-", "_") }}
  tags: 
    - "0.9.3"

- name: remove old sysvinit startup file 
  file: path=/etc/init.d/hostapd state=absent
  when: st.stat.exists == False
  tags: 
    - "0.9.3"

- name: remove old way of lunching ansible-pull
  file: path=/etc/dhcp/dhclient-exit-hooks.d/ansiblePullUpdate state=absent
  when: st.stat.exists == False
  tags: 
    - "0.9.3"


- ini_file: dest=/etc/ansible/facts.d/installed_software.fact
            section=upgrade
            option=ideascube
            value={{ ansible_local.installed_software.software.ideascube }}

- name: reload ansible_local
  setup: filter=ansible_local