---
- include_vars: group_vars/{{ ansible_architecture }}.yml

# Fix for the last Ideascube version

- name: Create ideascube cache folder
  file: path=/var/cache/ideascube/ state=directory owner=ideascube group=ideascube mode=755
  when: dev_sda.stat.exists == True and dev_mmcblk0.stat.exists == True

- name: Create a simlink for ideascube catalog
  file: src=/media/hdd/ideascube_cache dest=/var/cache/ideascube
  when: dev_sda.stat.exists == True and dev_mmcblk0.stat.exists == True

- name: Install the ideascube package
  apt: name=ideascube={{ ansible_local.device_list[generic_project_name].ideascube.version }} state=present update_cache=yes force=yes
